version: '3.0'

services:
    main:
        container_name: messanger-server
        build:
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            DATABASE_SERVER_NAME: ${DATABASE_SERVER_NAME}
            DATABASE_PORT: ${DATABASE_PORT}
            USER_NAME: ${USER_NAME}
            USER_PASSWORD: ${USER_PASSWORD}
        ports:
            - ${APPLICATION_PORT}:${CONTAINER_PORT}
        restart: always